### ISSUE TITLE
拉取master分支编译报错

### ISSUE THREAD

**Issue by charnet1019** [gsgs-libin/sre_cerebrum#1]
```
[root@slb sre_cerebrum]# yarn install
yarn install v1.22.19
warning ../package.json: No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > @ant-design-vue/pro-layout@1.0.11" has unmet peer dependency "umi-request@^1.2.11".
warning " > @ant-design-vue/pro-layout@1.0.11" has unmet peer dependency "vue-container-query@^0.1.0".
warning " > @ant-design/icons@4.7.0" has unmet peer dependency "react@>=16.0.0".
warning " > @ant-design/icons@4.7.0" has unmet peer dependency "react-dom@>=16.0.0".
warning "@ant-design/icons > rc-util@5.16.1" has unmet peer dependency "react@>=16.9.0".
warning "@ant-design/icons > rc-util@5.16.1" has unmet peer dependency "react-dom@>=16.9.0".
warning " > less-loader@5.0.0" has unmet peer dependency "webpack@^2.0.0 || ^3.0.0 || ^4.0.0".
[4/4] Building fresh packages...
[-/7] ⠂ waiting...
[6/7] ⠂ ant-design-vue
[-/7] ⠂ waiting...
[-/7] ⠂ waiting...
error /root/sre_cerebrum/node_modules/deasync: Command failed.
Exit code: 1
Command: node ./build.js
Arguments: 
Directory: /root/sre_cerebrum/node_modules/deasync
Output:
`linux-x64-node-16` exists; testing
Problem with the binary; manual build incoming
stdout=
err=Error: Command failed: /usr/bin/node quick-test.js
/root/sre_cerebrum/node_modules/bindings/bindings.js:135
  throw err;
  ^

Error: Could not locate the bindings file. Tried:
 → /root/sre_cerebrum/node_modules/deasync/build/deasync.node
 → /root/sre_cerebrum/node_modules/deasync/build/Debug/deasync.node
 → /root/sre_cerebrum/node_modules/deasync/build/Release/deasync.node
 → /root/sre_cerebrum/node_modules/deasync/out/Debug/deasync.node
 → /root/sre_cerebrum/node_modules/deasync/Debug/deasync.node
 → /root/sre_cerebrum/node_modules/deasync/out/Release/deasync.node
 → /root/sre_cerebrum/node_modules/deasync/Release/deasync.node
 → /root/sre_cerebrum/node_modules/deasync/build/default/deasync.node
 → /root/sre_cerebrum/node_modules/deasync/compiled/16.15.0/linux/x64/deasync.node
 → /root/sre_cerebrum/node_modules/deasync/addon-build/release/install-root/deasync.node
 → /root/sre_cerebrum/node_modules/deasync/addon-build/debug/install-root/deasync.node
 → /root/sre_cerebrum/node_modules/deasync/addon-build/default/install-root/deasync.node
 → /root/sre_cerebrum/node_modules/deasync/lib/binding/node-v93-linux-x64/deasync.node
    at bindings (/root/sre_cerebrum/node_modules/bindings/bindings.js:126:9)
    at Object.<anonymous> (/root/sre_cerebrum/node_modules/deasync/index.js:30:31)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/root/sre_cerebrum/node_modules/deasync/quick-test.js:3:13)
    at Module._compile (node:internal/modules/cjs/loader:1105:14) {
  tries: [
    '/root/sre_cerebrum/node_modules/deasync/build/deasync.node',
    '/root/sre_cerebrum/node_modules/deasync/build/Debug/deasync.node',
    '/root/sre_cerebrum/node_modules/deasync/build/Release/deasync.node',
    '/root/sre_cerebrum/node_modules/deasync/out/Debug/deasync.node',
    '/root/sre_cerebrum/node_modules/deasync/Debug/deasync.node',
    '/root/sre_cerebrum/node_modules/deasync/out/Release/deasync.node',
    '/root/sre_cerebrum/node_modules/deasync/Release/deasync.node',
    '/root/sre_cerebrum/node_modules/deasync/build/default/deasync.node',
    '/root/sre_cerebrum/node_modules/deasync/compiled/16.15.0/linux/x64/deasync.node',
    '/root/sre_cerebrum/node_modules/deasync/addon-build/release/install-root/deasync.node',
    '/root/sre_cerebrum/node_modules/deasync/addon-build/debug/install-root/deasync.node',
    '/root/sre_cerebrum/node_modules/deasync/addon-build/default/install-root/deasync.node',
    '/root/sre_cerebrum/node_modules/deasync/lib/binding/node-v93-linux-x64/deasync.node'
  ]
}

node:events:505
      throw er; // Unhandled 'error' event
      ^

Error: spawn node-gyp ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (node:internal/child_process:289:12)
    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn node-gyp',
```

**Comment by charnet1019** [comment]
[root@slb sre_cerebrum]# yarn --version
1.22.19

[root@slb sre_cerebrum]# node --version
v16.15.0

**Comment by charnet1019** [comment]
如果用release包则编译时报如下错误：
```
[root@slb sre_cerebrum-1.0.1]# yarn install
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
error An unexpected error occurred: "http://npm.meitu-int.com/rc-util/-/rc-util-5.14.0.tgz: Request failed \"403 Forbidden\"".
info If you think this is a bug, please open a bug report with the information provided in "/home/src/sre_cerebrum-1.0.1/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by dgsfor** [comment]
你好，我已经调整了main分支的代码了。
1.删除了yarn.lock文件
2.更新了一些代码，有关lint相关的

你可以直接重新拉取main分支的代码，来做编译构建。另外release包我删除了，应该是我之前上传的有问题，谢谢反馈~

**Comment by dgsfor** [comment]
最后，这个项目很久没有更新了，最近可能没有更多的时间花在这个上面，你如果觉得还可以的话，可以持续对他进行更新 ，谢谢 @charnet1019
